# Book flight tickets
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.yatra.com")
print(driver.title)
time.sleep(2)
driver.find_element(By.XPATH, "//a[@title='Round Trip']").click()
time.sleep(2)
depart_city = driver.find_element(By.XPATH, "//input[@id='BE_flight_origin_city']")
depart_city.click()
depart_city.send_keys('New Delhi')
time.sleep(5)
depart_city.send_keys(Keys.RETURN)
arrival_city = driver.find_element(By.XPATH, "//input[@id='BE_flight_arrival_city']")
arrival_city.click()
arrival_city.send_keys('Mumbai')
time.sleep(5)
arrival_city.send_keys(Keys.RETURN)
date_1 = driver.find_element(By.XPATH, "//input[@id='BE_flight_origin_date']")
date_1.click()
time.sleep(3)
date_1 = driver.find_element(By.XPATH, '//*[@id="24/05/2023"]')
date_1.click()
date_2 = driver.find_element(By.XPATH, '//input[@id="BE_flight_arrival_date"]')
date_2.click()
time.sleep(3)
date_2 = driver.find_element(By.XPATH, '//*[@id="26/05/2023"]')
date_2.click()
time.sleep(3)
nf = driver.find_element(By.XPATH, "//a[normalize-space()='Non Stop Flights']")
nf.click()
time.sleep(2)
clas = driver.find_element(By.XPATH, "//span[@class='txt-ellipses flight_passengerBox travellerPaxBox']")
clas.click()
passengers = driver.find_element(By.XPATH, "(//span[@class = 'ddSpinnerPlus'])[1]")
passengers.click()
time.sleep(3)
search = driver.find_element(By.XPATH, "//input[@value = 'Search Flights']")
search.click()
